export const ISR_CATEGORIES_PAGE_NUMBERS =
  process.env.NEXT_PUBLIC_ISR_CATEGORIES_PAGE_NUMBERS || 10;
export const ISR_PRODUCTS_PAGE_NUMBERS = process.env.NEXT_PUBLIC_ISR_PRODUCTS_PAGE_NUMBERS || 10;
